# Generated by Django 3.0.7 on 2020-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_xpaccount_xptransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpaccount',
            name='acc_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('asset', 'Asset'), ('income', 'Income')], default='expense', max_length=16),
        ),
    ]
