# Generated by Django 3.0.7 on 2020-06-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_xpaccount_xptransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xptransaction',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
