# Generated by Django 3.0.7 on 2020-06-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_xpaccount_acc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xptransaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
